//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.LobbyDetails"/> </summary
    public sealed class LobbyDetailsClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public LobbyDetailsClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "LobbyDetails";
            }
        }
        
        /// <summary>
        /// Call the CreateLobby method on the LobbyDetails microservice
        /// <see cref="Beamable.Microservices.LobbyDetails.CreateLobby"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> CreateLobby(string lobbyId, bool isPublic, string lobbyName, string gamemode)
        {
            object raw_lobbyId = lobbyId;
            object raw_isPublic = isPublic;
            object raw_lobbyName = lobbyName;
            object raw_gamemode = gamemode;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("lobbyId", raw_lobbyId);
            serializedFields.Add("isPublic", raw_isPublic);
            serializedFields.Add("lobbyName", raw_lobbyName);
            serializedFields.Add("gamemode", raw_gamemode);
            return this.Request<Beamable.Common.Unit>("LobbyDetails", "CreateLobby", serializedFields);
        }
        
        /// <summary>
        /// Call the GetLobbyConnectionDetails method on the LobbyDetails microservice
        /// <see cref="Beamable.Microservices.LobbyDetails.GetLobbyConnectionDetails"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> GetLobbyConnectionDetails(string lobbyId)
        {
            object raw_lobbyId = lobbyId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("lobbyId", raw_lobbyId);
            return this.Request<Beamable.Common.Unit>("LobbyDetails", "GetLobbyConnectionDetails", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersLobbyDetailsClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Boolean : MicroserviceClientDataWrapper<bool>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForLobbyDetailsClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<LobbyDetailsClient>();
        }
        
        public static LobbyDetailsClient LobbyDetails(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<LobbyDetailsClient>();
        }
    }
}
